run:
  total_gens: 10 
  npop: 5  # Population size
  log_level: "DEBUG"  # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
  rng_seed: 32000 # Seed used for RNG in entire loop (so ara, genes, + operators)

sim:
  ara_processes: 10 # Number of jobs for each antenna in arasim
  num_keys: 1  # Number of keys for XFdtd on user
  freq_num: 60
  freq_start: 83.33
  freq_step: 16.67
  nnt: 100000  # Total number of neutrinos thrown per antenna
  exp: 18  # Energy expontent 10^(exp)
  scale_factor: 1 # Fitness scale factor
  geo_factor: 1 # Fitness geometry factor

antennas:
  antenna: "HPOL"  # Options: "VPOL", "HPOL"

  vpol:
    radius: 0  # Symmetric radii? 
    length: 0  # Symmetric length?
    angle: 0  # Symmetric angle? 
    curved: 0  # Curved? 
    a: 0 
    b: 0
    separation: 0 # Feed distance evolves? 
    nsections: 0 # 

  hpol:
    # Define HPOL-specific params here if needed later
    # placeholder: null

ga: 
  # Operator Percentages
  reproduction: 0.1
  crossover: 0.4
  mutation: 0.5
  sigma: 0.05
  roulette: 0.8
  tournament: 0.2
  rank: 0 
  elite: 0 

job:
  single_batch: 0 # Toggle for single batch jobs
  max_jobs: 50 # Max jobs for your user
  threads_per_ara_job: 40 # Number of threads in any job requested (40 for pitzer on OSC)